export const INCREMENT_PANTS = "INCREMENT_PANTS";
export const INCREMENT_TSHIRTS = "INCREMENT_TSHIRTS";
export const INCREMENT_HATS = "INCREMENT_HATS";
export const INCREMENT_TOTALPANTS = "INCREMENT_TOTALPANTS";
export const INCREMENT_TOTALTSHIRTS = "INCREMENT_TOTALTSHIRTS";
export const INCREMENT_TOTALHATS = "INCREMENT_TOTALHATS";
export const TOTAL = "TOTAL";